# Generated by Django 3.2.8 on 2023-07-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('permission', models.SmallIntegerField(choices=[(0, 'guest'), (1, 'member'), (2, 'permission'), (3, 'admin')], verbose_name='')),
                ('create_time', models.IntegerField(default=0, verbose_name='创建时间')),
                ('balance', models.FloatField(default=0.0, verbose_name='余额')),
                ('status', models.SmallIntegerField(choices=[(0, 'ban'), (1, 'suspense'), (2, 'normal')], verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('avator', models.FileField(upload_to='avator/', verbose_name='logo')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
