# Generated by Django 4.2.4 on 2023-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('premium', models.IntegerField(default=0)),
                ('admin', models.IntegerField(default=0)),
            ],
        ),
    ]
