# Generated by Django 3.2.8 on 2023-07-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_key', models.CharField(max_length=64, verbose_name='用户标记')),
                ('browser', models.CharField(max_length=64, verbose_name='浏览器')),
                ('system', models.CharField(max_length=64, verbose_name='系统')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='marker_key',
            field=models.CharField(default=1, max_length=64, verbose_name='用户标记'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.FileField(upload_to='avator/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.SmallIntegerField(choices=[(0, 'guest'), (1, 'member'), (2, 'permission'), (3, 'admin')], verbose_name='权限'),
        ),
    ]
