# Generated by Django 4.2.4 on 2023-08-11 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('max_quorum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=128)),
                ('create_time', models.IntegerField()),
                ('take_seat_quorum', models.PositiveIntegerField(default=0, verbose_name='记录当前车队人数')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to='main.user', to_field='username')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_of_type', to='main.roomtype')),
                ('users', models.ManyToManyField(related_name='rooms_joined', to='main.user', verbose_name='记录当前车队包含的用户')),
            ],
        ),
    ]
