# Generated by Django 4.2.4 on 2023-08-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='level',
            field=models.CharField(max_length=128, unique=True, verbose_name='天数'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.FloatField(verbose_name='总价'),
        ),
    ]
