# Generated by Django 4.2.4 on 2023-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_roomtype_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
