# Generated by Django 4.2.4 on 2023-08-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_roomtype_level_alter_roomtype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users_favorited',
            field=models.ManyToManyField(blank=True, related_name='favorite_rooms', to='main.user'),
        ),
    ]
