# Generated by Django 3.2.8 on 2023-07-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_guest_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='browser',
            field=models.CharField(default='empty', max_length=128, verbose_name='浏览器'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='system',
            field=models.CharField(default='empty', max_length=128, verbose_name='系统'),
        ),
    ]
