# Generated by Django 4.2.4 on 2023-08-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_users_favorited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.IntegerField()),
                ('read', models.IntegerField()),
                ('from_room', models.ManyToManyField(related_name='from_who_room', to='main.room')),
                ('receive_user', models.ManyToManyField(related_name='receive', to='main.user')),
                ('send_user', models.ManyToManyField(related_name='send', to='main.user')),
            ],
        ),
    ]
