# Generated by Django 4.2.4 on 2023-08-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator_color',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
