# Generated by Django 3.2.8 on 2023-07-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230708_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='marker_key',
            field=models.CharField(max_length=32, verbose_name='用户标记'),
        ),
    ]
