# Generated by Django 4.2.4 on 2023-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_avator_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator_color',
            field=models.CharField(max_length=7),
        ),
    ]
