# Generated by Django 4.2.4 on 2023-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_avator_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='level',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
