# Generated by Django 4.2.4 on 2023-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_roomtype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='type',
            field=models.IntegerField(default=1, verbose_name='平台账号或者自备账号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='level',
            field=models.CharField(max_length=128, verbose_name='天数'),
        ),
    ]
