# Generated by Django 4.2.4 on 2023-08-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_roomtype_type_alter_roomtype_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.IntegerField(default=1, verbose_name='发车状态'),
            preserve_default=False,
        ),
    ]
