# Generated by Django 4.2.4 on 2023-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_room_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payqr',
            field=models.CharField(default='', max_length=128),
        ),
    ]
