# Generated by Django 4.2.4 on 2023-08-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_payed_qrcode_alter_order_payed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
