# Generated by Django 4.2.4 on 2023-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
