# Generated by Django 4.2.4 on 2023-08-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='qr_expire_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0, verbose_name='0未支付,1支付成功,2二维码到期'),
        ),
    ]
