# Generated by Django 4.2.4 on 2023-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.CharField(default=1, max_length=128, verbose_name='图片保存路径'),
            preserve_default=False,
        ),
    ]
