# Generated by Django 4.2.4 on 2023-08-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_room', to='main.room'),
        ),
    ]
