# Generated by Django 4.2.4 on 2023-08-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_usermail_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedChargeRoomAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('all_user_mail_info', models.CharField(max_length=64, verbose_name='记录关联的房间中的所有用户的mail_user表中的id')),
            ],
        ),
    ]
