# Generated by Django 4.2.4 on 2023-08-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_needchargeroomaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needchargeroomaccounts',
            name='all_user_mail_info',
            field=models.CharField(max_length=64, verbose_name='记录关联的房间中的所有用户的mail_user表中的id, =>[5,1,3,2,6]'),
        ),
        migrations.AlterField(
            model_name='needchargeroomaccounts',
            name='room_id',
            field=models.IntegerField(unique=True),
        ),
    ]
