# Generated by Django 4.2.4 on 2023-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_needchargeroomaccounts_all_user_mail_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
