# Generated by Django 4.2.4 on 2023-08-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_order_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
