# Generated by Django 4.2.4 on 2023-08-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_needchangepaaaword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='needchargeroomaccounts',
            name='room_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
