# Generated by Django 4.2.4 on 2023-09-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_accounttype_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=32)),
                ('visit_time', models.IntegerField()),
            ],
        ),
    ]
