# Generated by Django 4.2.4 on 2023-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='j8ijeg64', max_length=16, unique=True)),
                ('password', models.CharField(default='None', max_length=32)),
                ('level', models.BooleanField(default=False)),
                ('email', models.CharField(default='m3pfmj4@teamup.best', max_length=128, unique=True)),
                ('create_time', models.IntegerField(default=1694160325)),
                ('token', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
