# Generated by Django 4.2.4 on 2023-08-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('level', models.CharField(max_length=128, verbose_name='天数')),
                ('price', models.FloatField()),
                ('type', models.IntegerField(verbose_name='平台账号或者自备账号')),
                ('max_quorum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.IntegerField()),
                ('avator_color', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('premium', models.IntegerField(default=0)),
                ('admin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=128)),
                ('create_time', models.IntegerField()),
                ('uuid', models.CharField(max_length=6)),
                ('state', models.IntegerField(verbose_name='发车状态')),
                ('take_seat_quorum', models.PositiveIntegerField(default=0, verbose_name='记录当前车队人数')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to='main.user', to_field='username')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_of_type', to='main.roomtype')),
                ('users', models.ManyToManyField(related_name='rooms_joined', to='main.user', verbose_name='记录当前车队包含的用户')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('state', models.IntegerField(default=0, verbose_name='0未支付,1支付成功,2二维码到期')),
                ('price', models.FloatField()),
                ('qrcode', models.CharField(max_length=128)),
                ('create_time', models.IntegerField()),
                ('qr_expire_time', models.IntegerField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.user')),
            ],
        ),
    ]
