# Generated by Django 4.2.4 on 2023-09-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=16, unique=True)),
                ('password', models.CharField(default='empty', max_length=32)),
                ('level', models.IntegerField()),
                ('email', models.CharField(default='4q0o996@teamup.best', max_length=128, unique=True)),
                ('create_time', models.IntegerField(default=1694276185)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('price', models.CharField(max_length=32)),
                ('time', models.IntegerField()),
                ('support', models.TextField()),
                ('region', models.CharField(max_length=32)),
                ('state', models.BooleanField(default=True)),
                ('goods_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_type_name', to='main.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('trade_name', models.CharField(max_length=32, verbose_name='订单介绍')),
                ('pay_type', models.CharField(default='wechat', max_length=16)),
                ('order_amount', models.CharField(max_length=16, verbose_name='实际支付金额')),
                ('discount_code', models.CharField(default='empty', max_length=6)),
                ('state', models.BooleanField(default=False, verbose_name='支付状态')),
                ('create_time', models.IntegerField()),
                ('pay_qr_state', models.BooleanField(default=False, verbose_name='该订单是否被请求过二维码')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_info', to='main.goods')),
                ('order_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('seat_number', models.IntegerField()),
                ('seat_pin', models.IntegerField()),
                ('register_mail', models.CharField(max_length=64, unique=True)),
                ('expire_time', models.IntegerField()),
                ('user_buy_expire_time', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('dispatch_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch', to='main.user')),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_order', to='main.order')),
            ],
        ),
    ]
