# Generated by Django 4.2.4 on 2023-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694287136),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='20au0cu@teamup.best', max_length=128, unique=True),
        ),
    ]
