# Generated by Django 4.2.4 on 2023-09-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='sign',
            field=models.CharField(default=123123123, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694160698),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='wop4sod@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='826ufjgp', max_length=16, unique=True),
        ),
    ]
