# Generated by Django 4.2.4 on 2023-09-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_type_sale_type_stock_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='favorable',
            field=models.CharField(default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694287942),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='pdly64f@teamup.best', max_length=128, unique=True),
        ),
    ]
