# Generated by Django 4.2.4 on 2023-09-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_token_user_sign_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('max_seat', models.IntegerField()),
                ('current_seat', models.IntegerField()),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694166302),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='033m9zj@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='6xz4unjm', max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('seat_pin', models.CharField(default=None, max_length=4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account', to_field='account')),
            ],
        ),
    ]
