# Generated by Django 4.2.4 on 2023-09-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_alter_user_create_time_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True)),
                ('max_seat', models.IntegerField()),
                ('experience_price', models.CharField(max_length=16)),
                ('month_price', models.CharField(max_length=16)),
                ('two_month_price', models.CharField(max_length=16)),
                ('three_month_price', models.CharField(max_length=16)),
                ('half_year_price', models.CharField(max_length=16)),
                ('year_price', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='max_seat',
        ),
        migrations.RemoveField(
            model_name='account',
            name='price',
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.CharField(default=123124124, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694166982),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='yjadfjz@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='2px4pk5j', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accounttype', to_field='type'),
        ),
    ]
