# Generated by Django 4.2.4 on 2023-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_order_type_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_qr_state',
        ),
        migrations.AddField(
            model_name='order',
            name='qrcode',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='order',
            name='qrcode_expire_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694365252),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='2yuaq5j@teamup.best', max_length=128, unique=True),
        ),
    ]
