# Generated by Django 4.2.4 on 2023-09-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_accounttype_remove_account_max_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accounttype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694167394),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='ea99amu@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='drgv1e0j', max_length=16, unique=True),
        ),
    ]
