# Generated by Django 4.2.4 on 2023-09-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_order_pay_qr_state_order_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.goods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694381041),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='pn04nkl@teamup.best', max_length=128, unique=True),
        ),
    ]
