# Generated by Django 4.2.4 on 2023-09-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_account_type_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694167461),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='e8ij1jx@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='tqw4hhp4', max_length=16, unique=True),
        ),
    ]
