# Generated by Django 4.2.4 on 2023-09-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_accountgroup_account_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='current_seat',
            new_name='surplus_seat',
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694167542),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='bj11ipj@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='2qwsszxx', max_length=16, unique=True),
        ),
    ]
