# Generated by Django 4.2.4 on 2023-09-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_current_seat_account_surplus_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='rcl1da42zv4pc92m', max_length=32, unique=True)),
                ('trade_name', models.CharField(max_length=32)),
                ('pay_type', models.CharField(default='wechat', max_length=8)),
                ('order_amount', models.CharField(max_length=16, verbose_name='实际支付价格')),
                ('order_uid', models.CharField(max_length=16, verbose_name='订单用户名')),
                ('order_price', models.CharField(max_length=16, verbose_name='订单原本价格')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694226441),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='36jvz34@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='20togxfl', max_length=16, unique=True),
        ),
    ]
