# Generated by Django 4.2.4 on 2023-09-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_alter_user_create_time_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='use_time',
            field=models.IntegerField(default=1, verbose_name='购买时长'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='5vai9hcblb4ibvxn', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694227518),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='e6clys2@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='yfwzt1gi', max_length=16, unique=True),
        ),
    ]
