# Generated by Django 4.2.4 on 2023-09-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_use_time_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694227586),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='bz31zi7@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='cjchi6pg', max_length=16, unique=True),
        ),
    ]
