# Generated by Django 4.2.4 on 2023-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_order_expire_time_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_qrcode',
            field=models.TextField(default=None, verbose_name='支付二维码'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.BooleanField(default=False, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694229938),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='j335970@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='g08ucssn', max_length=16, unique=True),
        ),
    ]
