# Generated by Django 4.2.4 on 2023-09-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_discount_code_order_pay_qrcode_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694229986),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='macd1pw@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='6qtkz15f', max_length=16, unique=True),
        ),
    ]
