# Generated by Django 4.2.4 on 2023-09-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_discount_code_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_qrcode',
            field=models.TextField(default='', verbose_name='支付二维码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694230013),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='bgm3jn5@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='27e44j8i', max_length=16, unique=True),
        ),
    ]
