# Generated by Django 4.2.4 on 2023-09-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_order_pay_qrcode_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_expire_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694230508),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='hcxkv2m@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='rtgp2b6o', max_length=16, unique=True),
        ),
    ]
