# Generated by Django 4.2.4 on 2023-09-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_order_order_expire_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_qrcode',
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694230545),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='w9xlz9r@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='qnq1kwkd', max_length=16, unique=True),
        ),
    ]
