# Generated by Django 4.2.4 on 2023-09-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_create_time_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='use',
            field=models.BooleanField(default=False, verbose_name='该订单是否被使用'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694234443),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='6005ev7@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='8kdabdz4', max_length=16, unique=True),
        ),
    ]
