# Generated by Django 4.2.4 on 2023-09-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_order_use_alter_user_create_time_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='use',
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694234703),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='89g8v8m@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='7tp7raut', max_length=16, unique=True),
        ),
    ]
