# Generated by Django 4.2.4 on 2023-09-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_order_use_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.IntegerField(default=112, verbose_name='订单是否被请求二维码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694235159),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='vihjuts@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='umbfb1z7', max_length=16, unique=True),
        ),
    ]
