# Generated by Django 4.2.4 on 2023-09-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_order_order_time_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.IntegerField(default=1804235184, verbose_name='订单是否被请求二维码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694235189),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='jylq1l4@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='mn6z119o', max_length=16, unique=True),
        ),
    ]
