# Generated by Django 4.2.4 on 2023-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_order_order_time_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accountgroup_id',
            field=models.IntegerField(default=0, verbose_name='分配的账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694238653),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='nf9bdat@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='m6zqv2sr', max_length=16, unique=True),
        ),
    ]
