# Generated by Django 4.2.4 on 2023-08-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(default='random', max_length=6),
        ),
    ]
