# Generated by Django 4.2.4 on 2023-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_accountgroup_id_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_account_type',
            field=models.IntegerField(default=0, verbose_name='购买的类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694238793),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='rbywsiu@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='9c4425n5', max_length=16, unique=True),
        ),
    ]
