# Generated by Django 4.2.4 on 2023-08-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='begin_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountcode',
            name='effect',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountcode',
            name='end_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
