# Generated by Django 4.2.4 on 2023-09-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_buy_account_type_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694239160),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='dew2ne8@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='7kimjd2g', max_length=16, unique=True),
        ),
    ]
