# Generated by Django 4.2.4 on 2023-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_order_buy_account_type_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_account_regin',
            field=models.TextField(default='全球', verbose_name='购买的地区'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_account_type',
            field=models.TextField(verbose_name='购买的类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694241866),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='q3r7nn1@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='alfr51p0', max_length=16, unique=True),
        ),
    ]
