# Generated by Django 4.2.4 on 2023-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_order_buy_account_regin_alter_order_buy_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694242117),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='cud0g9s@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='xfww0wrr', max_length=16, unique=True),
        ),
    ]
