# Generated by Django 4.2.4 on 2023-08-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_usermail_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail',
            name='room',
        ),
    ]
