# Generated by Django 4.2.4 on 2023-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_order_order_id_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='region',
            field=models.CharField(default=12, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694252203),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='0gojal4@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='edb6ezi5', max_length=16, unique=True),
        ),
    ]
