# Generated by Django 4.2.4 on 2023-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_accounttype_region_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694253140),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='ld6x3ah@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='4587pdkm', max_length=16, unique=True),
        ),
    ]
