# Generated by Django 4.2.4 on 2023-09-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_accounttype_type_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expire_time',
            field=models.IntegerField(default=112, verbose_name='账号到期时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='expire_time',
            field=models.IntegerField(default=0, verbose_name='用户购买到期时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=1694255340),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='y15u06c@teamup.best', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='11vpcivt', max_length=16, unique=True),
        ),
    ]
