# Generated by Django 4.2.4 on 2023-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_roomtype_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='seat_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
