# Generated by Django 4.2.4 on 2023-08-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_discountcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needchangepaaaword',
            name='state',
            field=models.IntegerField(default=1, verbose_name='0未处理,1已处理'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needchangepaaaword',
            name='submit_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
