# Generated by Django 4.2.4 on 2023-09-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_account_distribute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='seat_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
