# Generated by Django 4.2.4 on 2023-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_account_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='region',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
