# Generated by Django 4.2.4 on 2023-09-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surplus_seat', models.IntegerField()),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=128)),
                ('expire_time', models.IntegerField(verbose_name='账号到期时间')),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('max_seat', models.IntegerField()),
                ('experience_price', models.CharField(max_length=16)),
                ('month_price', models.CharField(max_length=16)),
                ('two_month_price', models.CharField(max_length=16)),
                ('three_month_price', models.CharField(max_length=16)),
                ('half_year_price', models.CharField(max_length=16)),
                ('year_price', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('trade_name', models.CharField(max_length=32)),
                ('pay_type', models.CharField(default='wechat', max_length=8)),
                ('order_amount', models.CharField(max_length=16, verbose_name='实际支付价格')),
                ('order_uid', models.CharField(max_length=16, verbose_name='订单用户名')),
                ('order_price', models.CharField(max_length=16, verbose_name='订单原本价格')),
                ('use_time', models.IntegerField(verbose_name='购买时长')),
                ('discount_code', models.CharField(default='', max_length=6)),
                ('state', models.BooleanField(default=False, verbose_name='支付状态')),
                ('order_time', models.IntegerField(default=1804235184, verbose_name='订单是否被请求二维码')),
                ('accountgroup_id', models.IntegerField(default=0, verbose_name='分配的账号')),
                ('buy_account_type', models.TextField(verbose_name='购买的类型')),
                ('buy_account_regin', models.TextField(default='全球', verbose_name='购买的地区')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default='rc9dura3', max_length=16, unique=True)),
                ('password', models.CharField(default='None', max_length=32)),
                ('level', models.BooleanField(default=False)),
                ('email', models.CharField(default='89269ot@teamup.best', max_length=128, unique=True)),
                ('create_time', models.IntegerField(default=1694273424)),
                ('sign', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.TextField(verbose_name='支付二维码')),
                ('expirce_time', models.IntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('seat_pin', models.CharField(default=None, max_length=4)),
                ('expire_time', models.IntegerField(default=0, verbose_name='用户购买到期时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('used', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accounttype'),
        ),
    ]
