import Head from "next/head";
import NavBar from "../components/NavBar/index";
import Commodity from "../components/Commodity/index";
import Notify from "../components/Notify/index";
import Footer from "../components/Footer/index";
import Login from "../components/Login/index";
import Sub from "../components/Sub/index";
import Kefu from "../components/Kefu/index";
import styled from "styled-components";
import React from "react";

const Wrap = styled.div`
  .main {
    width: 1200px;
    margin: 0 auto;
  }
`;

export default function Home() {
  const [userinfo, setUserinfo] = React.useState({
    username: "",
    level: 0,
    showLogin: false,
  });

  const changeLogin = (type) => {
    setUserinfo({ ...userinfo, showLogin: type });
  };

  return (
    <Wrap>
      <Head>
        <title>Teamup-奈飞合租平台 流媒体合租 奈飞组队</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Notify />
      <NavBar login={changeLogin} />
      {userinfo.showLogin ? <Login close={changeLogin} /> : null}
      <main className="main">
        <Commodity />
        <Sub />
      </main>
      <Kefu />
      <Footer />
    </Wrap>
  );
}
